create database demo;
use demo;

create table traduccion(
id varchar(100) not null,
idioma char(2) not null,
llave char(50) not null,
valor varchar(300) not null
) ;

select * from traduccion;

insert into traduccion(id, idioma, llave, valor) values
('index','es','form','Formulario'),
('index','es','correo','Correo'),
('index','es','contra','Contraseña'),
('index','es','pais','País'),
('index','es','IP','IP'),
('index','es','codigoPais','Código de país'),
('index','es','guardar','Guardar'),
('index','es','Title','¿Desea ingresar los datos?'),
('index','es','Text','La información será enviada'),
('index','es','confirmButtonText','Si, enviar'),
('index','es','errorTitle','Error al enviar'),
('index','es','successTitle','Formulario enviado'),
('index','es','successText','Muchas gracias'),
('index','es','spancorreo','No ha ingresado el correo'),
('index','es','spancontra','No ha ingresado la contraseña'),
('index','es','placeholdercorreo','Escribe tu correo'),
('index','es','placeholdercontra','Escribe tu contraseña'), 
('index','en','form','Form'),
('index','en','correo','Email'),
('index','en','contra','Password'),
('index','en','pais','Country'),
('index','en','IP','IP'),
('index','en','codigoPais','Country Code'),
('index','en','guardar','Save'),
('index','en','Title','Do you want to send the data?'),
('index','en','Text','Information is going to be send'),
('index','en','confirmButtonText','Yes, send'),
('index','en','errorTitle','Error while sending'),
('index','en','successTitle','Form sent'),
('index','en','successText','Thank you'),
('index','en','spancorreo','You have not entered the email'),
('index','en','spancontra','You have not entered the password'),
('index','en','placeholdercorreo','Write your email'),
('index','en','placeholdercontra','Write your password'),
('formSolicitudPedidos','es','TitleDinamico','¿Desea enviar el formulario?'),
('formSolicitudPedidos','es','TextDinamico','La información será guardada'),
('formSolicitudPedidos','es','ConfirmDinamico','Si, enviar'),
('formSolicitudPedidos','es','DenyDinamico','No, salir'),
('formSolicitudPedidos','es','TitleDinamicoError','Error'),
('formSolicitudPedidos','es','TitleDinamicoCancelado','Cancelado'),
('formSolicitudPedidos','es','TitleFacturarDinamico','¿Desea facturar?'),
('formSolicitudPedidos','es','TextFacturarDinamico','El pedido será realizado'),
('formSolicitudPedidos','es','TitleFacturarDinamicoSuccess','Compra realizada'),
('formSolicitudPedidos','es','tituloSolicitudPedidos','Solicitud de pedido'),
('formSolicitudPedidos','es','DatosCliente','Datos del cliente'),
('formSolicitudPedidos','es','NomCompleto','Nombre completo'),
('formSolicitudPedidos','es','correo','Correo electrónico'),
('formSolicitudPedidos','es','Nacionalidad','Nacionalidad'),
('formSolicitudPedidos','es','Estadounidense','Estadounidense'),
('formSolicitudPedidos','es','NumIndentificacion','Número de identificación'),
('formSolicitudPedidos','es','NumTelefono','Número de teléfono'),
('formSolicitudPedidos','es','Direccion','Dirección'),
('formSolicitudPedidos','es','Productos','Productos'),
('formSolicitudPedidos','es','AgregarProducto','Agregar producto'),
('formSolicitudPedidos','es','NombreT','Nombre'),
('formSolicitudPedidos','es','CantidadT','Cantidad'),
('formSolicitudPedidos','es','QuitarT','Quitar'),
('formSolicitudPedidos','es','Sacos','Sacos'),
('formSolicitudPedidos','es','Enviar','Enviar'),
('formSolicitudPedidos','es','Cancelar','Cancelar'),
('formSolicitudPedidos','es','NomCompleto','Nombre Completo'),
('formSolicitudPedidos','es','correo','Correo electrónico'),
('formSolicitudPedidos','es','Nacionalidad','Nacionalidad'),
('formSolicitudPedidos','es','NumIndentificacion','Número de identificación'),
('formSolicitudPedidos','es','NumTelefono','Número teléfono'),
('formSolicitudPedidos','es','Direccion','Dirección'),
('formSolicitudPedidos','es','productoT','Producto'),
('formSolicitudPedidos','es','CantidadT','Cantidad'),
('formSolicitudPedidos','es','precioUniT','Precio Unitario'),
('formSolicitudPedidos','es','totalIVA','Total con IVA'),
('formSolicitudPedidos','es','Facturar','Facturar'),
('formSolicitudPedidos','es','InfoTarjeta','Indique la información de su tarjeta'),
('formSolicitudPedidos','es','MetodoPago','Método de pago'),
('formSolicitudPedidos','es','TarjetaCredito','Tarjeta de crédito'),
('formSolicitudPedidos','es','TarjetaDebito','Tarjeta de débito'),
('formSolicitudPedidos','es','NomTarjeta','Nombre de la tarjeta'),
('formSolicitudPedidos','es','NumTarjeta','Número de tarjeta'),
('formSolicitudPedidos','es','FechaVence','Fecha de vencimiento'),
('formSolicitudPedidos','es','Comprobante','Comprobante'),
('formSolicitudPedidos','es','Enviar','Enviar'),
('formSolicitudPedidos','es','Cancelar','Cancelar'),
('formSolicitudPedidos','es','PLComprobante','Factura'),
('formSolicitudPedidos','es','PLNomCompleto','Ingrese su nombre completo'),
('formSolicitudPedidos','es','PLcorreo','Ingrese su correo'),
('formSolicitudPedidos','es','PLNumIndentificacion','Ingrese su número de identificación'),
('formSolicitudPedidos','es','PLNumTelefono','Ingrese su número de teléfono'),
('formSolicitudPedidos','es','PLNomTarjeta','Ingrese el nombre de su tarjeta'),
('formSolicitudPedidos','es','PLNumTarjeta','Ingrese el número de su tarjeta'),
('formSolicitudPedidos','es','PLDireccion','Ingrese su dirección'),

('global','es','Inicio','Inicio'),
('global','es','GestionUsuarios','Gestión de usuarios'),
('global','es','ConsultaExistencia','Consulta de existencia'),
('global','es','SolicitudPedidos','Solicitud de pedidos'),
('global','es','Sobre','sobre'),
('global','es','Calidad','Calidad'),
('global','es','Productos','Productos'),
('global','es','Contacto','Contáctanos'),
('global','en','Derechos','2022, SACOS EL SALVADOR | Reservados todos los derechos.'),
('global','es','Inglés','Inglés'),
('global','es','Español','Español'),

('formGestionUsuario','en','guardar','Guardar'),
('formGestionUsuario','en','id','ID'),
('formGestionUsuario','en','nombre','Nombre'),
('formGestionUsuario','en','apellido','Apellido'),
('formGestionUsuario','en','numeroidentificacion','Número de identificación'),
('formGestionUsuario','en','correo','Correo'),
('formGestionUsuario','en','nacionalidad','Nacionalidad'),
('formGestionUsuario','en','direccion','Dirección'),
('formGestionUsuario','en','telefono','Teléfono'),
('formGestionUsuario','en','accionModificar','Acción de modificar'),
('formGestionUsuario','en','accionDeshabilitar','Acción de deshabilitar'),
('formGestionUsuario','en','modificar','Modificar'),
('formGestionUsuario','en','deshabilitar','Deshabilitar'),

('formConsultaExistencia','en','numeroFactura','Número de factura'),
('formConsultaExistencia','en','cliente','Cliente'),
('formConsultaExistencia','en','comprobante','Comprobante'),
('formConsultaExistencia','en','impuesto','Impuesto'),
('formConsultaExistencia','en','total','Total'),
('formConsultaExistencia','en','estado','Estado'),
('formConsultaExistencia','en','acciones','Acciones'),
('formConsultaExistencia','en','detalles','Detalles'),
('formConsultaExistencia','en','reporte','Reporte'),
('formConsultaExistencia','en','anular','Anular'),
('formConsultaExistencia','en','consultaExistencia','Consulta de existencia'),
('formConsultaExistencia','en','detallesCliente','Detalles del cliente'),
('formConsultaExistencia','en','nombre','Nombre'),
('formConsultaExistencia','en','correo','Correo'),
('formConsultaExistencia','en','nacionalidad','Nacionalidad'),
('formConsultaExistencia','en','nIdentdad','Número de Identidad'),
('formConsultaExistencia','en','telefono','Teléfono'),
('formConsultaExistencia','en','direccion','Dirección'),
('formConsultaExistencia','en','detalleProducto','Detalles del producto'),
('formConsultaExistencia','en','producto','Producto'),
('formConsultaExistencia','en','cantidad','Cantidad'),
('formConsultaExistencia','en','precioUnitario','Precio Unitario'),
('formConsultaExistencia','en','totalIva','Total con IVA'),
('formConsultaExistencia','en','metodoPago','Método de pago'),
('formConsultaExistencia','en','estado','Estado'),
('formConsultaExistencia','en','enviar','Enviar'),
('formConsultaExistencia','en','cerrar','Cerrar'),

('formInicio','en','texto','En Sacos Sintéticos Centroamericanos ofrecemos soluciones de empaque, productos tejidos y no tejidos de polipropileno, actuando como líderes en el mercado salvadoreño, basando nuestro crecimiento en el mercado de la exportación.'),
('formInicio','en','Inicio','Inicio'),
('formSolicitudPedidos','en','TitleDinamico','Do you want to submit the form?'),
('formSolicitudPedidos','en','TextDinamico','The information will be saved'),
('formSolicitudPedidos','en','ConfirmDinamico','Yes, send'),
('formSolicitudPedidos','en','DenyDinamico','No, exit'),
('formSolicitudPedidos','en','TitleDinamicoError','Error'),
('formSolicitudPedidos','en','TitleDinamicoCancelado','Canceled'),
('formSolicitudPedidos','en','TitleFacturarDinamico','Do you want to invoice?'),
('formSolicitudPedidos','en','TextFacturarDinamico','The order will be placed'),
('formSolicitudPedidos','en','TitleFacturarDinamicoSuccess','Purchase made'),
('formSolicitudPedidos','en','tituloSolicitudPedidos','Pre-Order Form'),
('formSolicitudPedidos','en','DatosCliente','Customer data'),
('formSolicitudPedidos','en','NomCompleto','Full name'),
('formSolicitudPedidos','en','correo','Email'),
('formSolicitudPedidos','en','Nacionalidad','Nationality'),
('formSolicitudPedidos','en','Estadounidense','American'),
('formSolicitudPedidos','en','NumIndentificacion','Identification number'),
('formSolicitudPedidos','en','NumTelefono','Phone Number'),
('formSolicitudPedidos','en','Direccion','Address'),
('formSolicitudPedidos','en','Productos','Products'),
('formSolicitudPedidos','en','AgregarProducto','Add Product'),
('formSolicitudPedidos','en','NombreT','Name'),
('formSolicitudPedidos','en','CantidadT','Quantity'),
('formSolicitudPedidos','en','QuitarT','Remove'),
('formSolicitudPedidos','en','Sacos','Sacks'),
('formSolicitudPedidos','en','Enviar','Send'),
('formSolicitudPedidos','en','Cancelar','Cancel'),
('formSolicitudPedidos','en','NomCompleto','Full name'),
('formSolicitudPedidos','en','correo','Email'),
('formSolicitudPedidos','en','Nacionalidad','Nationality'),
('formSolicitudPedidos','en','NumIndentificacion','Identification number'),
('formSolicitudPedidos','en','NumTelefono','Phone number'),
('formSolicitudPedidos','en','Direccion','Address'),
('formSolicitudPedidos','en','productoT','Product'),
('formSolicitudPedidos','en','CantidadT','Quantity'),
('formSolicitudPedidos','en','precioUniT','Unit Price'),
('formSolicitudPedidos','en','totalIVA','Total with IVA'),
('formSolicitudPedidos','en','Facturar','Invoice'),
('formSolicitudPedidos','en','InfoTarjeta','Enter your card information'),
('formSolicitudPedidos','en','MetodoPago','Payment method'),
('formSolicitudPedidos','en','TarjetaCredito','Credit card'),
('formSolicitudPedidos','en','TarjetaDebito','Debit card'),
('formSolicitudPedidos','en','NomTarjeta','Card name'),
('formSolicitudPedidos','en','NumTarjeta','Card number'),
('formSolicitudPedidos','en','FechaVence','Expiration date'),
('formSolicitudPedidos','en','Comprobante','Voucher'),
('formSolicitudPedidos','en','Enviar','Send'),
('formSolicitudPedidos','en','Cancelar','Cancel'),
('formSolicitudPedidos','en','PLComprobante','Receipt'),
('formSolicitudPedidos','en','PLNomCompleto','Enter your full name'),
('formSolicitudPedidos','en','PLcorreo','Enter your email'),
('formSolicitudPedidos','en','PLNumIndentificacion','Enter your ID number'),
('formSolicitudPedidos','en','PLNumTelefono','Enter your phone number'),
('formSolicitudPedidos','en','PLNomTarjeta','Enter your card name'),
('formSolicitudPedidos','en','PLNumTarjeta','Enter your card number'),
('formSolicitudPedidos','en','PLDireccion','Enter your address'),

('global','en','Inicio','Home'),
('global','en','GestionUsuarios','User Management'),
('global','en','ConsultaExistencia','Inventory look-up'),
('global','en','SolicitudPedidos','Pre-Order Form'),
('global','en','Sobre','About'),
('global','en','Calidad','Quality'),
('global','en','Productos','Products'),
('global','en','Derechos','2022, SACOS EL SALVADOR | All rights reserved.'),
('global','en','Contacto','Contact us'),
('global','en','Inglés','English'),
('global','en','Español','Spanish'),

('formGestionUsuario','en','guardar','Save'),
('formGestionUsuario','en','id','ID'),
('formGestionUsuario','en','nombre','Name'),
('formGestionUsuario','en','apellido','Last name'),
('formGestionUsuario','en','numeroidentificacion','ID Number'),
('formGestionUsuario','en','correo','Email'),
('formGestionUsuario','en','nacionalidad','Nationality'),
('formGestionUsuario','en','direccion','Address'),
('formGestionUsuario','en','telefono','Phone'),
('formGestionUsuario','en','accionModificar','Modify action'),
('formGestionUsuario','en','accionDeshabilitar','Disable action'),
('formGestionUsuario','en','modificar','Modify'),
('formGestionUsuario','en','deshabilitar','Disable'),

('formConsultaExistencia','en','numeroFactura','Invoice number'),
('formConsultaExistencia','en','cliente','Customer'),
('formConsultaExistencia','en','comprobante','Receipt'),
('formConsultaExistencia','en','impuesto','Tax'),
('formConsultaExistencia','en','total','Total'),
('formConsultaExistencia','en','estado','Status'),
('formConsultaExistencia','en','acciones','Actions'),
('formConsultaExistencia','en','detalles','Details'),
('formConsultaExistencia','en','reporte','Report'),
('formConsultaExistencia','en','anular','Cancel'),
('formConsultaExistencia','en','consultaExistencia','Inventory look-up'),
('formConsultaExistencia','en','detallesCliente','Customer Details'),
('formConsultaExistencia','en','nombre','Name'),
('formConsultaExistencia','en','correo','Email'),
('formConsultaExistencia','en','nacionalidad','Nationality'),
('formConsultaExistencia','en','nIdentdad','Identity Number'),
('formConsultaExistencia','en','telefono','Phone'),
('formConsultaExistencia','en','direccion','Address'),
('formConsultaExistencia','en','detalleProducto','Product Details'),
('formConsultaExistencia','en','producto','Product'),
('formConsultaExistencia','en','cantidad','Quantity'),
('formConsultaExistencia','en','precioUnitario','Unit Price'),
('formConsultaExistencia','en','totalIva','Total with IVA'),
('formConsultaExistencia','en','metodoPago','Payment method'),
('formConsultaExistencia','en','estado','Status'),
('formConsultaExistencia','en','enviar','Send'),
('formConsultaExistencia','en','cerrar','Close'),

('formInicio','en','texto','In Sacos Sintéticos Centroamericanos we offer packaging solutions, woven and non-woven polypropylene products, acting as leaders in the Salvadoran market, basing our growth in the export market.'),
('formInicio','en','Inicio','Home');

